### ISSUE TITLE
sudo is not always required

### ISSUE THREAD

**Issue by skaji** [perl-actions/install-with-cpm#1]
`sudo` is not always required. It's nice we can configure it.
And even if `sudo` is required, `cpm installl --sudo ..` is better than `sudo cpm install ...`

**Comment by atoomic** [comment]
yeap I m adding several extra configuration options, sudo is going to be one of it
view https://github.com/perl-actions/install-cpm#example-usage

**Comment by atoomic** [comment]
this is going to be fixed in release v1.1
