### ISSUE TITLE
use fatpacked cpm

### ISSUE THREAD

**Issue by skaji** [perl-actions/install-with-cpm#2]
There is no functional difference between the fatpacked cpm `https://git.io/cpm` and CPAN module `App::cpm`.
I think it is important to make CI fast. 
So why don't you simply use the fatpacked cpm?

**Comment by atoomic** [comment]
I grabbed the incorrect command by mistake lol

**Comment by atoomic** [comment]
this is going to be fixed in release v1.1 96043e4b
